@startuml "Use case diagram"
left to right direction
actor User #lightblue
actor Database #lightblue
package "Use case" #lightblue {
    usecase Login
    usecase ca as "Create account"
    usecase mp as "Manage project
        ---
        <b>extension points
        ExtensionPoint
        Manage user permissions
        Get project process raport
    "
    usecase ct as "CRUD tasks"
    usecase pr as "Project raport"
    usecase mup as "Manage user permissions"
    usecase au as "Add user"
    usecase Chat
    usecase mt as "Manage tasks"
    usecase Calendar
    usecase pn as "Push notifications"
}
User -- Login
Login ~~> ca : <<include>>
ca -- Database
mp -- Database
User -- mp
ct ~~> mp : <<extend>>
pr ~~> mp : <<extend>>
mup ~~> mp : <<extend>>
au ~~> mup
User -- mt
User -- Calendar
mt <~~ pn : <<include>>
Calendar <~~ pn : <<include>>
User -- Chat
Chat -- Database

@enduml
