# Generated by Django 4.1.5 on 2023-01-03 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadImage',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image_s3_path',
        ),
    ]
